#!/bin/bash
for (( a=1; a<=0xF; a++ )) ; do
	for (( b=0; b<=0xF; b++ )) ; do
		#[[ $a -eq 0 ]] && code=`printf "%x" $b` 			# printf "%x " $b #echo -n "$b " #
		#[[ $a -ne 0 ]] && code=`printf "%x\n" $(( 16 * a + b ))` 	# printf "%x " $(( 16 * a + b )) # echo -n "$(( 16 * a + b )) " 
		#echo -n "$(( 16 * a + b )) "
		#printf "%x " $(( 16 * a + b ))
		#printf "%n %x " $(( 16 * a + b ))  $(( 16 * a + b )) 
		  #printf "%x " $a$b
		  #code=`printf "%x\n" $a$b`
		#code=$(( 16 * a + b )) 
		hex=$(printf "%X" $(( 16 * a + b )) )
		[[ $hex == "1B" ]] && echo -ne "$hex:  "
		[[ $hex != "1B" ]] && echo -ne "$hex:\\x$hex  "
	done
	echo
#echo
done
