#!/bin/sh
# Makes a non git directory to a new private bitbucket repository with all files added to initial commit
# Usage = enter your bitbucket GITUSER and password in the script

echo -n Enter password for $GITUSER: && read -s PASSWORD && echo

echo "git init..."
git init

echo "#About" > readme.md
#TODO IF 
echo "git add -A ..."
git add -A .

echo "Initial commit..."
git commit -m "Initial commit"

echo "...creating new remote repo on bitbucket with name ${PWD##*/}"
curl --user $GITUSER:$PASSWORD https://api.bitbucket.org/1.0/repositories/ --data name=${PWD##*/} --data is_private='true' -k -s | jq ''

echo "adding new repo remote URL https://$GITUSER@bitbucket.org/$GITUSER/ ..."
#git remote add origin https://$GITUSER@bitbucket.org/$GITUSER/${PWD##*/}.git
git remote add origin ssh://git@bitbucket.org/$GITUSER/${PWD##*/}.git

echo "git push -u origin --all..."
git push -u origin --all
git push -u origin --tags
