#!/bin/bash
# https://habrahabr.ru/post/119436/
# http://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
ansi-codes() {
              #0  Reset all attributes
              #1  Bright
              #2  Dim
              #4  Underscore  
                #5  Blink
              #7  Reverse
                #8  Hidden
      for a in 2 0 1 4 7 5; do # 5 8
              [ $a -eq 2 ] && echo "Dim (2):" 
              [ $a -eq 0 ] && echo "Norm (0-reset):" 
              [ $a -eq 4 ] && echo "Underscore (4):" 
              [ $a -eq 1 ] && echo "Bright (1):" 
              [ $a -eq 7 ] && echo "Reverse (7):" 
              [ $a -eq 5 ] && echo "Blink (5):" 
              for (( f=1; f<=9; f++ )) ; do # #f in 1 8 9
                      # 
                      for b in 0 8 9 ; do # (( b=0; b<=9; b++ )); do # 1-7: background
                              #echo -ne "f=$f b=$b" 
                              echo -ne "\\033[${a};3${f};4${b}m"
                              echo -ne "\\\\\\\\033[${a};3${f};4${b}m"
                              echo -ne "\\033[0m "
                      done
              echo
              done
              #echo
      done
      echo
      }

# Foreground Colours
#30 Black
#31 Red
#32 Green
#33 Yellow
#34 Blue
#35 Magenta
#36 Cyan
#37 White

# Background Colours
#40 Black
#41 Red
#42 Green
#43 Yellow
#44 Blue
#45 Magenta
#46 Cyan
#47 White

ansi-codes