#!/bin/sh
#USERNAME=...
echo CLONE remote repo to local folder

#todo: test for empty curr_dir
echo -n Enter password for $USERNAME: && read -s PASSWORD && echo
curr_dir=${PWD##*/}

echo "CLONING repo $SVN_NEW/svn/$curr_dir..."
cd ..
svn checkout "$SVN_NEW/svn/$curr_dir"
cd $curr_dir