#!/bin/sh
#USERNAME=...
echo CLONE remote repo to local folder

[[ "$SVN_REPOS" = "" ]] && echo "Var SVN_REPOS is not detected ! Run at first: . varadd SVN_REPOS '<url>'" && exit 1

#todo: test for empty curr_dir
echo -n Enter password for $USERNAME: && read -s PASSWORD && echo
curr_dir=${PWD##*/}

echo "CLONING repo $SVN_REPOS/svn/$curr_dir..."
cd ..
svn checkout --username="$USERNAME" --password="$PASSWORD" "$SVN_REPOS/svn/$curr_dir"
cd $curr_dir