#!/bin/sh
#EX: fget https://raw.githubusercontent.com/xtender/xt_runstats/master/xt_runstats.sql
FNAME=$1
#URL=$2
#cd $SYSTEMROOT/System32/WindowsPowerShell/v1.0
#ls powershell.exe
#$SYSTEMROOT/System32/WindowsPowerShell/v1.0/powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "((new-object net.webclient).DownloadFile('$URL/$FNAME', '$FNAME'))"
$SYSTEMROOT/System32/WindowsPowerShell/v1.0/powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "((new-object net.webclient).DownloadFile('$FNAME', [System.IO.Path]::GetFileName('$FNAME') ))"
