#!/usr/bin/bash
SAVEIFS=$IFS
IFS=$(echo -en "\n\b");
FILES=($(ls -1 --color=none)) # --ignore='lav' --ignore='!*' --quoting-style=shell '' --quoting-style=c-""
 #echo ${FILES[*]}
IFS=$SAVEIFS

count=${#FILES[*]}
count=$[count	 - 1]
#for FILE in ${FILES[@]}; do
ii=0
while [ $ii -le $count ] ; do
	 #echo $ii
	 #echo ${FILES[$ii]}
	FILE=${FILES[$ii]}
	 # for --quoting-style=c
	 # 	cmd="echo $FILE"
	 # 	FILE=$(eval $cmd)
	du -s "$FILE"
	ii=$[ii + 1]
  done
