#!/bin/bash
echo "ADDED   DELETED"
git log -last --pretty=format:"%h%x09%Creset%an%x09%x09%s" --decorate -10 --numstat $* | grep -v "^$"  | grep -vE "^[0-9a-f]{7}" | grep -vE "^-"

#git log --numstat --pretty --oneline 0f5d22e..HEAD -- <filename>