#!/bin/bash
[[ "$GITHOST" == "" ]] && echo "\$GITHOST not defined!" && exit
msg=$1
#pwd | tr 'a-z' 'A-Z'
git add -A .
[[ "$msg" == "" ]] && msg=up
git commit -m "$(echo $GITHOST)_$msg" # $(date +'%d.%m.%y_%k:%M')
gilf 1
# exit