#!/bin/bash
[[ "$GITHOST" == "" ]] && echo "\$GITHOST not defined!" && exit
msg=$1
#pwd | tr 'a-z' 'A-Z'
get_branch() { 
	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ \1/' 
}
echo BRANCH:$(get_branch)
git add -A .
[[ "$msg" == "" ]] && msg=up
git commit -m "$(echo $GITHOST)_$msg" # $(date +'%d.%m.%y_%k:%M')
gilf 1
# exit