#!/bin/bash
canondirslashes() {
	local p
	p="$(echo $1 | tr '\\' '/')" 
	echo ${p%/}
	}

canonpath() {
	canondirslashes "$( test "${1:1:1}" != : && echo $1 || echo $(echo /${1::1} | tr [A-Z] [a-z])${1:2} )" 
	}