#!/usr/bin/bash
#enlist values from user's PATH to rows
if [[ "$1" = "sys" ]]; then KEY="HKLM\SYSTEM\ControlSet001\Control\Session Manager\Environment"; fi
if [[ "$1" = "SYS" ]]; then KEY="HKLM\SYSTEM\ControlSet001\Control\Session Manager\Environment"; fi
if [[ "$1" = "user" ]]; then KEY="HKCU\Environment"; fi
if [[ "$1" = "USER" ]]; then KEY="HKCU\Environment"; fi
if [[ "$1" = "" ]]; then KEY="HKCU\Environment"; fi
if [[ "$KEY" = "" ]]; then KEY="HKCU\Environment"; fi

ALL=no
if [[ "$1" = "all" ]]; then ALL=yes; fi
#Reg.exe query HKCU\\Environment -v PATH
#Reg.exe query $KEY -v PATH | grep PATH | sed -n 	"s/\([^[:blank:]]\+\)/\1/p" # "/.*/p"
#echo -n '    PATH    REG_EXPAND_SZ    C:\app\RailsInstaller\Ruby2.1.0\' | sed -n "s/^\([[:blank:]]\+[^[:blank:]]\+\)/\1/p"
#    PATH    REG_EXPAND_SZ    C:\app\RailsInstaller\Ruby2.1.0\
#echo -n '    PATH    REG_EXPAND_SZ    C:\app\RailsInstaller\Ruby2.1.0\' | sed "s/\([[:blank:]]\+[^[:blank:]]\+\)\{2\}[[:blank:]]\+\(.*\)/\2/g"
#C:\app\RailsInstaller\Ruby2.1.0\

#echo ==$KEY==
#echo Reg.exe query $KEY -v PATH
#Reg.exe query "$KEY" -v PATH
PATH2=$(Reg.exe query "$KEY" -v PATH | grep PATH | sed "s/\([[:blank:]]\+[^[:blank:]]\+\)\{2\}[[:blank:]]\+\(.*\)/\2/g")
if [[ "$2" = "all" ]]; then ALL=yes; fi
if [[ "$2" = "ALL" ]]; then ALL=yes; fi
if [[ "$ALL" = "yes" ]]; then
	echo  --------------------------------------------------------------------------------
	echo "$PATH2"
	echo  --------------------------------------------------------------------------------
  fi

SAVEIFS=$IFS
IFS=';'
RES=
read -ra ARR <<< "$PATH2"
for VALUE in "${ARR[@]}"; do
	#echo $VALUE
	if [ "$RES" = "" ]; then
		RES="$VALUE"
	  else
	  	RES=$(printf "%s\n%s" "$RES	" "$VALUE")
	  fi
  done
IFS=$SAVEIFS
echo "$RES" | sort