#!/usr/bin/bash
#cut value from PATH
#ex.  pathdel "%ODA_HOME%\bin"
#ex.  pathdel c:\\app\\git\\cmd

NEWITEM=$1
if [[ "$1" = "" ]]; then exit; fi

KEY="HKCU\Environment" #user's path
KEY_SYS="HKLM\SYSTEM\ControlSet001\Control\Session Manager\Environment" #system path

#разделить path
#Reg.exe query "HKCU\Environment" -v PATH | grep PATH | sed "s/\([[:blank:]]\+[^[:blank:]]\+\)\{2\}[[:blank:]]\+\(.*\)/\2/g"
PATH2=$(Reg.exe query "$KEY" -v PATH | grep PATH | sed "s/\([[:blank:]]\+[^[:blank:]]\+\)\{2\}[[:blank:]]\+\(.*\)/\2/g") # | sed "s/%\([^%;]\+\)%/$\U\1/g"
echo OLD: $PATH2
PATH_NEW=""
SAVEIFS=$IFS
IFS=';'
read -ra ARR <<< "$PATH2"

#по каждому item
for VALUE in "${ARR[@]}"; do
	#echo $VALUE
	#если совпадает то удалить
	if [[ ! "$VALUE" = "$NEWITEM" ]]; then
		if [[ "$PATH_NEW" = "" ]]; then
			PATH_NEW="$VALUE"
		  else
			PATH_NEW="$PATH_NEW;$VALUE"
		  fi
	  fi
  done
IFS=$SAVEIFS

#добавить new item
echo NEW: $PATH_NEW
if [[ "$PATH_NEW" = "" ]]; then
	echo "empty"
	return
  fi
setx PATH "$PATH_NEW" > nul

#PATH_NEW=$(Reg.exe query "$KEY" -v PATH | grep PATH | sed "s/\([[:blank:]]\+[^[:blank:]]\+\)\{2\}[[:blank:]]\+\(.*\)/\2/g")
#PATH_SYS=$(Reg.exe query "$KEY_SYS" -v PATH | grep PATH | sed "s/\([[:blank:]]\+[^[:blank:]]\+\)\{2\}[[:blank:]]\+\(.*\)/\2/g")
PATH_SYS=$(Reg.exe query "$KEY_SYS" -v PATH | grep PATH | sed "s/\([[:blank:]]\+[^[:blank:]]\+\)\{2\}[[:blank:]]\+\(.*\)/\2/g" | sed "s/%\([^%;]\+\)%/$\U\1/g")
#PATH_SYS=$(Reg.exe query "HKLM\SYSTEM\ControlSet001\Control\Session Manager\Environment" -v PATH | grep PATH | sed "s/\([[:blank:]]\+[^[:blank:]]\+\)\{2\}[[:blank:]]\+\(.*\)/\2/g")
#echo $PATH_SYS
PATH_NEW=$(echo "$PATH_NEW" | sed "s/%\([^%;]\+\)%/$\U\1/g")
PATH_CURR="$PATH_NEW;$PATH_SYS"
PATH_CURR=$(eval "echo \"$PATH_CURR \"")
PATH_CURR=${PATH_CURR//\\/\/}
#TODO: REPLACE C to $SYSTEMDRIVE
PATH_CURR=${PATH_CURR//C:/\/c}
PATH_CURR=${PATH_CURR//c:/\/c}
PATH_CURR=${PATH_CURR//;/:}
#echo $PATH_CURR
PATH="$PATH_CURR"
export PATH
pathlist