#!/usr/bin/bash

echo "Use syntax: sw-svn"
[[ "$APPS" = "" ]] && echo "\$APPS is not defined; setup it (ex. in ~/.bash_profile or by 'varadd APPS <path>') and reopen shell" && exit 1

if [ -d $APPS/portablesvn1.8 ]; then
	echo "set default svn to 1.8"
	mv "$APPS/portablesvn" "$APPS/portablesvn1.7"
	mv "$APPS/portablesvn1.8" "$APPS/portablesvn"
  else
	if [ -d $APPS/portablesvn1.7 ]; then
		echo "set default svn to 1.7"
		mv "$APPS/portablesvn" "$APPS/portablesvn1.8"
		mv "$APPS/portablesvn1.7" "$APPS/portablesvn"
	  fi
  fi