#!/usr/bin/bash
#add  var/value to permanent user's environment
#ex1: . varadd GOPATH "$USERPROFILE/go"
#ex2: . varadd GOPATH c:\\app\\go\\work
#ex2: . varadd GOPATH 'c:\app\go\work'

if [[ "$1" = "" ]]; then
	echo 1st param VAR_NAME is absent !
	exit
  fi
if [[ "$2" = "" ]]; then
	echo 2nd param VAR_VALUE is absent !
	exit;
  fi
VAR_NAME=$1
VAR_VALUE=$2

KEY="HKLM\SYSTEM\ControlSet001\Control\Session Manager\Environment"

VAR_VALUE_OLD=
VAR_VALUE_OLD=$(Reg.exe query "$KEY" -v $VAR_NAME 2>nul | grep $VAR_NAME | sed "s/\([[:blank:]]\+[^[:blank:]]\+\)\{2\}[[:blank:]]\+\(.*\)/\2/g")
if [[ "$VAR_VALUE_OLD" != "" ]]; then
	echo [OLD] $VAR_NAME: $VAR_VALUE_OLD
  fi

echo [NEW] $VAR_NAME: $VAR_VALUE
if [[ "$VAR_VALUE" = "" ]]; then
	echo "VAR_VALUE is empty"
	exit
  fi
#echo setx $VAR_NAME "$VAR_VALUE"
setx -m $VAR_NAME "$VAR_VALUE" >nul

export $VAR_NAME
